spring:
  application:
    name: thymeleaf-poc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
  datasource:
    url: jdbc:mysql://localhost:3306/root
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver